language: android
jdk:
  - oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-27"
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.1
    - android-27
    #- extra-google-m2repository
    #- extra-android-m2repository

before_script:
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api

script:
    - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
    - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace
#script:
  # - ./gradlew build connectedCheck
