language: android
jdk:
  - oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-27"
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.1
    - android-27
    #- extra-google-m2repository
    #- extra-android-m2repository

before_script:
    - chmod +x gradlew      #Grant permissions
script:
  - ./gradlew build connectedCheck
