language: android
sudo: required
before_install:
- chmod +x gradlew
script:
- ./gradlew clean build -i --continue
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-24
